/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package booklibrary;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.ZonedDateTime;
import java.util.Calendar;



/**
 *
 * @author safi
 */
public class RentFrame extends javax.swing.JFrame {

    /**
     * Creates new form RentFrame
     */
    public RentFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tcustid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tbookid = new javax.swing.JTextField();
        tcusname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tcusphone = new javax.swing.JTextField();
        tbookrentprice = new javax.swing.JTextField();
        tbookname = new javax.swing.JTextField();
        tbooktype = new javax.swing.JTextField();
        tbookquantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ttimefromy = new javax.swing.JTextField();
        ttimeto = new javax.swing.JTextField();
        ttimefromm = new javax.swing.JTextField();
        ttimefromyd = new javax.swing.JTextField();
        ttimetom = new javax.swing.JTextField();
        ttimetod = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        trntdays = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        trentprice = new javax.swing.JTextField();
        lapreq = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lapsaved = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setLayout(null);

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Go to Main Window( X )");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(530, 10, 220, 20);

        jLabel3.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Customer ID :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 130, 110, 30);

        tcustid.setBackground(new java.awt.Color(51, 51, 51));
        tcustid.setForeground(new java.awt.Color(255, 255, 255));
        tcustid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tcustidKeyReleased(evt);
            }
        });
        jPanel2.add(tcustid);
        tcustid.setBounds(180, 130, 180, 30);

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Book ID :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 180, 90, 18);

        tbookid.setBackground(new java.awt.Color(51, 51, 51));
        tbookid.setForeground(new java.awt.Color(255, 255, 255));
        tbookid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbookidKeyReleased(evt);
            }
        });
        jPanel2.add(tbookid);
        tbookid.setBounds(180, 170, 180, 30);

        tcusname.setBackground(new java.awt.Color(51, 51, 51));
        tcusname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(tcusname);
        tcusname.setBounds(550, 130, 190, 30);

        jLabel4.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Customer name:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(410, 140, 130, 20);

        tcusphone.setBackground(new java.awt.Color(51, 51, 51));
        tcusphone.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(tcusphone);
        tcusphone.setBounds(550, 180, 190, 30);

        tbookrentprice.setBackground(new java.awt.Color(51, 51, 51));
        tbookrentprice.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(tbookrentprice);
        tbookrentprice.setBounds(550, 380, 190, 30);

        tbookname.setBackground(new java.awt.Color(51, 51, 51));
        tbookname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(tbookname);
        tbookname.setBounds(550, 230, 190, 30);

        tbooktype.setBackground(new java.awt.Color(51, 51, 51));
        tbooktype.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(tbooktype);
        tbooktype.setBounds(550, 280, 190, 30);

        tbookquantity.setBackground(new java.awt.Color(51, 51, 51));
        tbookquantity.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(tbookquantity);
        tbookquantity.setBounds(550, 330, 190, 30);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Customer phone:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(410, 190, 130, 18);

        jLabel10.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Book type:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(410, 290, 90, 18);

        jLabel11.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Book Rent Price:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(410, 390, 130, 18);

        jLabel12.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Book quantity:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(410, 340, 120, 18);

        jLabel13.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Book name :");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(410, 240, 110, 18);

        jLabel6.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Renting Time ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(140, 280, 130, 18);

        ttimefromy.setBackground(new java.awt.Color(51, 51, 51));
        ttimefromy.setForeground(new java.awt.Color(255, 255, 255));
        ttimefromy.setToolTipText("");
        jPanel2.add(ttimefromy);
        ttimefromy.setBounds(40, 360, 40, 30);

        ttimeto.setBackground(new java.awt.Color(51, 51, 51));
        ttimeto.setForeground(new java.awt.Color(255, 255, 255));
        ttimeto.setToolTipText("");
        jPanel2.add(ttimeto);
        ttimeto.setBounds(220, 360, 40, 30);

        ttimefromm.setBackground(new java.awt.Color(51, 51, 51));
        ttimefromm.setForeground(new java.awt.Color(255, 255, 255));
        ttimefromm.setToolTipText("");
        jPanel2.add(ttimefromm);
        ttimefromm.setBounds(90, 360, 40, 30);

        ttimefromyd.setBackground(new java.awt.Color(51, 51, 51));
        ttimefromyd.setForeground(new java.awt.Color(255, 255, 255));
        ttimefromyd.setToolTipText("");
        jPanel2.add(ttimefromyd);
        ttimefromyd.setBounds(140, 360, 40, 30);

        ttimetom.setBackground(new java.awt.Color(51, 51, 51));
        ttimetom.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(ttimetom);
        ttimetom.setBounds(270, 360, 40, 30);

        ttimetod.setBackground(new java.awt.Color(51, 51, 51));
        ttimetod.setForeground(new java.awt.Color(255, 255, 255));
        ttimetod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ttimetodKeyReleased(evt);
            }
        });
        jPanel2.add(ttimetod);
        ttimetod.setBounds(320, 360, 40, 30);

        jLabel16.setFont(new java.awt.Font("Lucida Handwriting", 1, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText(" Year");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(220, 340, 40, 15);

        jLabel17.setFont(new java.awt.Font("Lucida Handwriting", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Month");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(270, 340, 50, 15);

        jLabel18.setFont(new java.awt.Font("Lucida Handwriting", 1, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("  Day");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(320, 340, 40, 15);

        jLabel15.setFont(new java.awt.Font("Lucida Handwriting", 1, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("  Day");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(140, 340, 40, 15);

        jLabel8.setFont(new java.awt.Font("Lucida Handwriting", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Month");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(90, 340, 50, 15);

        jLabel7.setFont(new java.awt.Font("Lucida Handwriting", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText(" Year");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(40, 340, 40, 15);

        jLabel9.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("To :");
        jLabel9.setToolTipText("");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(220, 310, 70, 18);

        jLabel19.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Total rent Price");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(520, 440, 140, 18);

        trntdays.setBackground(new java.awt.Color(51, 51, 51));
        trntdays.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(trntdays);
        trntdays.setBounds(440, 490, 40, 30);

        jLabel20.setFont(new java.awt.Font("Lucida Handwriting", 1, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Days");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(440, 470, 40, 15);

        jLabel22.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Search for Customer Information");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(50, 60, 330, 20);

        trentprice.setBackground(new java.awt.Color(51, 51, 51));
        trentprice.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(trentprice);
        trentprice.setBounds(520, 490, 220, 30);

        lapreq.setFont(new java.awt.Font("Lucida Handwriting", 1, 10)); // NOI18N
        lapreq.setForeground(new java.awt.Color(153, 0, 0));
        jPanel2.add(lapreq);
        lapreq.setBounds(30, 90, 350, 30);

        jLabel23.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Rent Information");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(510, 60, 160, 20);

        jLabel21.setFont(new java.awt.Font("Lucida Handwriting", 1, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Price");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(520, 470, 130, 15);

        jLabel14.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("From :");
        jLabel14.setToolTipText("");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(40, 310, 70, 18);

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Save ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(40, 490, 330, 28);

        lapsaved.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        lapsaved.setForeground(new java.awt.Color(153, 0, 0));
        lapsaved.setToolTipText("");
        jPanel2.add(lapsaved);
        lapsaved.setBounds(50, 440, 320, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booklibrary/book2 - Copy.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 780, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
Connection c ;
Statement s ;
ResultSet r ;
ResultSet r1 ;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new ChoseFrame().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tcustidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcustidKeyReleased
        try {
            c =DriverManager.getConnection("jdbc:ucanaccess://D:/LibertyBookDatabase.accdb");
            s =c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            r =s.executeQuery("select * from customer where [customer id]  like "+"'"+tcustid.getText()+"%'");
            r.next();
            
            tcusname.setText(r.getString("customer name"));
            tcusphone.setText(r.getString("customer phone"));
            lapsaved.setText("");
            if (tcustid.getText().equals(""))
            {
            tcusname.setText("");
            tcusphone.setText("");
            }
            
            
            
        } catch (SQLException e) {
            tcusname.setText("No Data");
            tcusphone.setText("No Data");
        }





        
    }//GEN-LAST:event_tcustidKeyReleased

    private void tbookidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbookidKeyReleased
 try {
            c =DriverManager.getConnection("jdbc:ucanaccess://D:/LibertyBookDatabase.accdb");
            s =c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            r1 =s.executeQuery("select * from books where [book id]  like "+"'"+tbookid.getText()+"%'");
            r1.next();
            
            lapsaved.setText("");
            tbookname.setText(r1.getString("book name"));
            tbooktype.setText(r1.getString("book type"));
            tbookquantity.setText(r1.getInt("book quantity")+"");
            tbookrentprice.setText(r1.getDouble("book rent price")+"");
            
            if (tbookid.getText().equals(""))
            {
            tbookname.setText("");
            tbooktype.setText("");
            tbookquantity.setText("");
            tbookrentprice.setText("");
            }
            
            
            
        } catch (SQLException e) {
            tbookname.setText("No Data");
            tbooktype.setText("No Data");
            tbookquantity.setText("No Data");
            tbookrentprice.setText("No Data");
        }



        
    }//GEN-LAST:event_tbookidKeyReleased

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
//String t =new SimpleDateFormat("YYYY/MM/dd  hh:mm").format(Calendar.getInstance().getTime());
       String y =new SimpleDateFormat("YYYY").format(Calendar.getInstance().getTime());
       ttimefromy.setText(y);
       String m =new SimpleDateFormat("MM").format(Calendar.getInstance().getTime());
       ttimefromm.setText(m);
       String d =new SimpleDateFormat("dd").format(Calendar.getInstance().getTime());
       ttimefromyd.setText(d);
       
       
       
       
       
       
       
       String yt =new SimpleDateFormat("YYYY").format(Calendar.getInstance().getTime());
       ttimeto.setText(yt);
       String mt =new SimpleDateFormat("MM").format(Calendar.getInstance().getTime());
       ttimetom.setText(mt);
       String dt =new SimpleDateFormat("dd").format(Calendar.getInstance().getTime());
       ttimetod.setText(dt);



        
    }//GEN-LAST:event_formWindowActivated

    private void ttimetodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ttimetodKeyReleased
 if (ttimetod.getText().equals("")||tbookrentprice.getText().equals(""))
 {
    lapreq.setText(" Search for Data in Customer ID and Book ID Fields");
      
        
 }
 
 else{
        
        String fs = ttimefromyd.getText();
      int f =Integer.parseInt(fs);
      
      
       String ts = ttimetod.getText();
      int t =Integer.parseInt(ts);
      
      int days =t-f;
      
      String price =tbookrentprice.getText();
      double fee =Double.parseDouble(price);
      
      trntdays.setText(days+"");
      
      
      trentprice.setText(days*fee+"");
        

 }

       
    }//GEN-LAST:event_ttimetodKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 try{
        Statement  sr =c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
        ResultSet   rr =sr.executeQuery("select * from [rental books] "); 
        rr.moveToInsertRow();
        
        rr.updateString("customer id", tcustid.getText());
        rr.updateString("book id",tbookid.getText());
        rr.updateString("customer name", tcusname.getText());
        rr.updateString("customer phone",tcusphone.getText());
        rr.updateString("book name", tbookname.getText());
        rr.updateString("book type",tbooktype.getText());
        rr.updateString("book quantity", tbookquantity.getText());
        rr.updateString("book rent price",tbookrentprice.getText());
        rr.updateString("rent days", trntdays.getText());
        rr.updateString("rent price",trentprice.getText());
        rr.insertRow();
        
        
        Connection c1 =DriverManager.getConnection("jdbc:ucanaccess://D:/LibertyBookDatabase.accdb");
            Statement  srq =c1.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            ResultSet   rqunt=srq.executeQuery("select * from Books where [book id]  like "+"'"+tbookid.getText()+"%'");
            rqunt.next();
            int qunt = Integer.parseInt(rqunt.getInt("book quantity")+"");
            int min = 1;
            int allqunt =qunt-min ;
            rqunt.updateInt("book quantity",allqunt);
            rqunt.updateRow();
            lapsaved.setText("All Information Saved in The Database");
             rr=sr.executeQuery("select * from [rental books]"); 
        
        
        
        }
        catch(Exception e)
        {
        
            e.printStackTrace();
        }




       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line argumentsDateFormat d =new SimpleDateFormat("yyyy/mm/dd  hh:mm:ss");
        CalendarData da =new CalendarData
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lapreq;
    private javax.swing.JLabel lapsaved;
    private javax.swing.JTextField tbookid;
    private javax.swing.JTextField tbookname;
    private javax.swing.JTextField tbookquantity;
    private javax.swing.JTextField tbookrentprice;
    private javax.swing.JTextField tbooktype;
    private javax.swing.JTextField tcusname;
    private javax.swing.JTextField tcusphone;
    private javax.swing.JTextField tcustid;
    private javax.swing.JTextField trentprice;
    private javax.swing.JTextField trntdays;
    private javax.swing.JTextField ttimefromm;
    private javax.swing.JTextField ttimefromy;
    private javax.swing.JTextField ttimefromyd;
    private javax.swing.JTextField ttimeto;
    private javax.swing.JTextField ttimetod;
    private javax.swing.JTextField ttimetom;
    // End of variables declaration//GEN-END:variables
}
